var appES = {
    "equalizer.label.datos": 'Datos',
    "equalizer.label.ordenar": 'Ordenar',
    "equalizer.label.presentacion": 'Presentación',
    "equalizer.label.colores": 'Colores y Leyendas',
    "equalizer.label.cabecerasyetiquetas": 'Cabeceras y etiquetas',
    "equalizer.label.cabecera": 'Cabeceras',
    "equalizer.label.superponeretiquetas": 'Superponer etiquetas',
    "equalizer.label.etiquetashojas": 'Etiquetas de hojas',
    "equalizer.label.etiquetasvalores": 'Etiquetas de valores',
    "equalizer.label.titulos": 'Títulos',
    "equalizer.label.dimensiones": 'Dimensiones',
    "equalizer.label.medidas": 'Medidas',
    "equalizer.label.ascendente": 'Ascendente',
    "equalizer.label.descendente": 'Descendente',
    "equalizer.label.valoresextremos": 'Incluir valores extremos',
    "equalizer.label.vertical": 'Vertical',
    "equalizer.label.horizontal": 'Horizontal',
    "equalizer.label.agrupado": 'Agrupado',
    "equalizer.label.apilado": 'Apilado',
    "equalizer.label.valoresperdidos": 'Valores perdidos',
    "equalizer.label.mostrarhuecos": 'Mostrar como huecos',
    "equalizer.label.mostrarconexiones": 'Mostrar como conexiones',
    "equalizer.label.mostrarceros": 'Mostrar como ceros',
    "equalizer.label.mostrarpuntos": 'Mostrar puntos de datos',
    "equalizer.label.tamanioburbuja": 'Tamaño de burbuja',
    "equalizer.label.puntosfluctuacion": 'Puntos de fluctuación',
    "equalizer.label.activado": 'Activado',
    "equalizer.label.desactivado": 'Desactivado',
    "equalizer.label.personalizado": 'Personalizado',
    "equalizer.label.colorunico": 'Color único',
    "equalizer.label.porDimension": 'Por dimensión',
    "equalizer.label.porMedida": 'Por medida',
    "equalizer.label.multicolor": 'Multicolor',
    "equalizer.label.esquemacolor": 'Esquema de color',
    "equalizer.label.mostrarleyenda": 'Mostrar leyenda',
    "equalizer.label.mostrartitulo": 'Mostrar títulos',
    "equalizer.label.mostraretiqueta": 'Mostrar etiqueta',
    "equalizer.label.titulo": 'Título',
    "equalizer.label.subtitulo": 'Subtítulo',
    "equalizer.label.piepagina": 'Nota a pie de página',
    "equalizer.label.posicionleyenda": 'Posición de leyenda',
    "equalizer.label.posicion": 'Posición',
    "equalizer.label.automatico": 'Automático',
    "equalizer.label.derecha": 'Derecha',
    "equalizer.label.final": 'Final',
    "equalizer.label.izquierda": 'Izquierda',
    "equalizer.label.principio": 'Principio',
    "equalizer.label.etiquetavalores": 'Etiquetas de valores',
    "equalizer.label.capas": 'Capas',
    "equalizer.label.configuracionmapa": 'Configuraciones de mapa',
    "equalizer.label.idiomamapa": 'Idioma del mapa',
    "equalizer.label.capa.puntos": 'Capa de puntos',
    "equalizer.label.capa.grafico": 'Capa de gráfico',
    "equalizer.label.capa.lineas": 'Capa de lineas',
    "equalizer.label.capa.densidad": 'Capa de densidad',
    "equalizer.label.capa.area": 'Capa de área',
    "equalizer.label.capa.fondo": 'Capa de fondo',
    "equalizer.label.mapabase": 'Mapa base',
    "equalizer.label.prederminado": 'Predeterminado',
    "equalizer.label.palido": 'Pálido',
    "equalizer.label.satelite": 'Satélite',
    "equalizer.label.ninguna": 'Ninguna',
    "equalizer.label.todos": 'Todos',
    "equalizer.label.cuota": 'Cuota',
    "equalizer.label.valores": 'Valores',
    "equalizer.label.ingles": 'Ingles',
    "equalizer.label.local": 'Local',
    "equalizer.label.zoomauto": 'Zoom automático',
    "equalizer.label.mostrarcapa": 'Mostrar capa',
    "equalizer.label.tamanioburbuja": 'Tamaño de burbuja',
    "equalizer.label.rangoburbuja": 'Rango de tamaño de la burbuja',
    "equalizer.label.rangotriangulo": 'Tamaño de triángulo',
    "equalizer.label.rangocuadrado": 'Tamaño de cuadrado',
    "equalizer.label.rangopentagono": 'Tamaño de pentágono',
    "equalizer.label.rangohexagono": 'Tamaño de hexágono',
    "equalizer.label.rangotarta": 'Tamaño del gráfico de tarta',
    "equalizer.label.rangolinea": 'Ancho de línea',
    "equalizer.label.radioinfluencia": 'Radio de influencia',
    "equalizer.label.alto": 'Alto',
    "equalizer.label.ancho": 'Ancho',
    "equalizer.label.navegacion": 'Navegación',
    "equalizer.label.etiquetas": 'Etiquetas',
    "equalizer.label.linea": 'Linea',
    "equalizer.label.area": 'Área',
    "equalizer.label.escalalogaritmica": 'Escala logarítmica',
    "equalizer.label.tarta": 'Tarta',
    "equalizer.label.donut": 'Donut',
    "equalizer.label.colorespersistentes": 'Colores persistentes',
    "equalizer.label.expandirtodo": 'Expandir todo',
    "equalizer.label.contraertodo": 'Contraer todo',
    "equalizer.label.tablatotales": 'Totales',
    "equalizer.label.desplazamiento": 'Desplazamiento',
    "equalizer.label.inmovilizarColumna": 'Inmovilizar primera columna',
    "equalizer.label.desHorizontal": 'Desplazamiento horizontal',
    "equalizer.label.ajustesTexto": 'Ajustes de texto multilinea',
    "equalizer.label.textoCabecera": 'Ajustar texto de cabecera',
    "equalizer.label.textoCelda": 'Ajustar texto de celda',
    "equalizer.label.filtros": "Filtros",
    "equalizer.btn.guardar": 'Guardar',
    "equalizer.btn.aplicar": 'Aplicar',
    "equalizer.btn.cancelar": 'Cancelar',
    "equalizer.btn.cerrar": 'Cerrar',
    "equalizer.btn.descartar": 'Descartar',
    "equalizer.title.mover": 'Mover',
    "equalizer.title.ascendente": 'Ascendente',
    "equalizer.title.descendente": 'Descendente',
    "equalizer.title.vertical": 'Vertical',
    "equalizer.title.horizontal": 'Horizontal',
    "equalizer.modal.atencion": 'Atención',
    "equalizer.modal.aviso": 'No se han guardado los cambios.',
    "equalizer.modal.avisoClose": 'Descartar cambios.',
    "equalizer.modal.cambios": '¿Aplicar los cambios?',
    "equalizer.modal.cambiosexplicacion": 'Todos los cambios se aplicarán a las propiedades del objeto.',
    "equalizer.modal.errormensaje": 'La selección ha creado una inconsistencia.',
    "equalizer.language.spaniol": 'Español',
    "equalizer.language.ingles": 'Ingles',
    "equalizer.language.frances": 'Frances',
    "contextmenu.label.menuexploracion": 'Abrir menú de exploración',
    "contextmenu.label.verdatos": 'Ver datos',
    "contextmenu.label.vergrafico": 'Ver gráfico',
    "contextmenu.label.exportimagen": 'Exportar como imagen',
    "contextmenu.label.exportpdf": 'Exportar a PDF',
    "contextmenu.label.exportdatos": 'Exportar datos',
    "contextmenu.label.expandirtodo": 'Expandir todo',
    "contextmenu.label.contraertodo": 'Contraer todo',
    "views.login.seleccionar": "Seleccionar Idioma",
    "views.acciones.marcadores": "Marcadores",
    "views.acciones.ayuda": "Ayuda",
    "views.acciones.configuracion": "Configuración",
    "views.acciones.aniadirmarcadores": "Añadir Marcador",
    "views.acciones.mas": "Más",
    "views.acciones.filtros": "Filtros",
    "views.acciones.bloquear": "Bloquear",
    "views.acciones.desbloquear": "Desbloquear",
    "views.acciones.limpiarselecciones": "Limpiar selecciones",
    "views.acciones.crearmarcadores": "Crear nuevo marcador",
    "views.acciones.seleccionartodos": "Seleccionar todos",
    "views.acciones.eliminarseleccionados": "Eliminar seleccionados",
    "views.acciones.OKbookmark": "Se ha creado el marcador",
    "views.acciones.KObookmark": "Debe introducir el nombre del marcador",
    "views.acciones.CrearBookmark": "Se ha creado el marcador",
    "views.acciones.EliminarBookmark": "Se ha eliminado el marcador",
    "views.acciones.Bookmarkexiste": "Ya existe un marcador con este título. Asigne otro título al marcador.",
    "views.acciones.seeliminaraBookmar": "Se eliminará el marcador.",
    'views.modal.crearmarcador': "Crear marcador",
    'views.modal.editarmarcador': "Editar marcador",
    "views.modal.crearmarcadortitulo": "Título",
    "views.modal.crearmarcadordescripcion": "Descripción",
    "views.modal.cerrar": "Cerrar",
    "views.modal.exportar": "Exportar",
    "views.modal.crear": "Crear",
    "views.modal.continuar": "Continuar",
    "views.modal.aceptar": "Aceptar",
    "views.modal.atencion": "Atención",
    "views.modal.accionnoback": "Esta acción no se puede deshacer. Desea continuar?",
    "views.modal.pdf": "Configuraciones de PDF",
    "views.modal.tamaniopapel": "Tamaño de papel",
    "views.modal.carta": "Carta",
    "views.modal.orientacion": "Orientación",
    "views.modal.vertical": "Vertical",
    "views.modal.apaisado": "Apaisado",
    "views.modal.opcionesaspecto": "Opciones de ratio de aspecto",
    "views.modal.actual": "Mantener tamaño actual",
    "views.modal.ajustar": "Ajustar a la página",
    "views.label.selecciones": "Selecciones",
    "views.label.filtros": "Filtros",
    "views.label.glosario": "Glosario",
    "views.label.cerrar": "Cerrar",
    "views.label.DimensionesMedidas": "Dimensiones y Medidas",
    "views.label.buscar": "Buscar",
    "template.label.template": "Personalizar plantilla",
    "template.label.themes": "Temas personalizados",
    "template.label.sidebarimages": "Imagen de fondo de la barra lateral",
    "template.label.sidebarcolor": "Color de fondo de la barra lateral",
    "template.label.headercolor": "Color de fondo de la cabecera",
    "template.label.menucolor": "Color item menú",
    "template.label.backgroundimage": "Imagen de fondo",
    "template.label.saveconfig": "Guardar configuración",
    "template.label.cliente": "Cliente",
    "template.label.proyecto": "Proyecto",
    "template.label.enlazarhoja": "Enlazar a hoja",
    "template.label.seleccionarhoja": "Seleccione una hoja",
    "views.idioma.es": "Español",
    "views.idioma.en": "Ingles",
    "views.idioma.fr": "Frances",

    "treepermissions.titles.roles": "Roles",
    "treepermissions.titles.groups": "Grupos",
    "treepermissions.titles.users": "Usuarios",
    "treepermissions.titles.functionality": "Opciones",
    "treepermissions.titles.identification": "Información personal",
    "treepermissions.titles.rulesapplied": "Reglas aplicadas",
    "treepermissions.actions.selectall": "seleccionar todos",
    "treepermissions.actions.newuser": "nuevo usuario",
    "treepermissions.actions.newgroup": "nuevo grupo",
    "treepermissions.actions.newrole": "nuevo rol",
    "treepermissions.placeholder.search": "buscar...",
    "treepermissions.buttons.new": "Nuevo",
    "treepermissions.buttons.new.role": "Rol",
    "treepermissions.buttons.new.group": "Grupo",
    "treepermissions.buttons.new.user": "Usuario",
    "treepermissions.buttons.assign": "Asignar",
    "treepermissions.buttons.delete": "Eliminar",
    "treepermissions.buttons.rules": "Reglas",
    "treepermissions.buttons.save": "Guardar",
    "treepermissions.buttons.add": "Añadir",
    "treepermissions.buttons.accept": "Aceptar",
    "treepermissions.buttons.cancel": "Cancelar",
    "treepermissions.buttons.close": "Cerrar",
    "treepermissions.buttons.replace": "Reemplazar",
    "treepermissions.buttons.edit": "Editar",
    "treepermissions.buttons.expandall": "Expandir todo",
    "treepermissions.buttons.collapseall": "Contraer todo",
    "treepermissions.rules.empty": "No hay reglas para mostrar",
    "treepermissions.modals.userform.user": "Usuario",
    "treepermissions.modals.userform.firstname": "Nombre",
    "treepermissions.modals.userform.lastname": "Apellidos",
    "treepermissions.modals.userform.domain": "Dominio",
    "treepermissions.modals.userform.gender": "Género",
    "treepermissions.modals.userform.email": "e-Mail",
    "treepermissions.modals.userform.address": "Dirección",
    "treepermissions.modals.userform.phone": "Teléfono",
    "treepermissions.modals.userform.role": "Rol",
    "treepermissions.modals.userform.birthday": "Cumpleaños",
    "treepermissions.modals.delete.title": "¿Quieres eliminar lo seleccionado?",
    "treepermissions.modals.assign.title": "Asignar grupos",
    "treepermissions.modals.assign.body": "¿Desea añadir o reemplazar los grupos seleccionados?",
    "treepermissions.modals.assign.role.title": "Asignar rol",
    "treepermissions.modals.assign.role.body": "¿Desea reemplazar el rol seleccionado?",
    "treepermissions.modals.delete.rule.title": "Eliminar la regla",
    "treepermissions.modals.delete.rule.body": "¿Quieres eliminar la regla '{{rule}}'?",

    "treepermissions.modals.save.label": "Opciones de guardado",
    "treepermissions.modals.save.title": "¿Qué quieres guardar?",
    "treepermissions.modals.save.section1": "Opciones",
    "treepermissions.modals.save.section1.opt1": "Añadir los permisos a los usuarios",
    "treepermissions.modals.save.section1.opt1small": "Se añadirán los permisos a los usuarios sin eliminar los ya creados.",
    "treepermissions.modals.save.section1.opt2": "Reemplazar permisos seleccionados",
    "treepermissions.modals.save.section1.opt2small": "Los permisos antiguos serán borrados y reemplazados por los seleccionados.",
    "treepermissions.modals.save.section1.opt3": "Crear una regla",
    "treepermissions.modals.save.section1.opt3small": "Se creará una regla que aplique los permisos a la selección. Es necesario haber seleccionado un rol o un grupo.",
    "treepermissions.modals.save.section2": "Selecciones",
    "treepermissions.modals.save.section2.opt1": "Solo se aplica a usuarios seleccionados",
    "treepermissions.modals.save.section2.opt2": "Se aplica a usuarios seleccionados y relacionados",
    "treepermissions.modals.save.section3": "Nombre de la regla",
    "treepermissions.modals.save.section3.replace": "La regla ya existe, ¿quieres reemplazarla?",
    "treepermissions.modals.save.section3.required": "Es necesario un nombre de regla",
    "treepermissions.modals.save.section3.placeholder": "Escribe el nombre de la regla...",

    "treepermissions.toast.permissionsload": '¡Permisos cargados correctamente!',
    "treepermissions.toast.roleupdate": "Rol actualizado con éxito",
    "treepermissions.toast.rolecreate": "Rol creado con éxito",
    "treepermissions.toast.groupupdate": "Grupo actualizado con éxito",
    "treepermissions.toast.groupcreate": "Grupo creado con éxito",
    "treepermissions.toast.roledelete": "El rol '{{role}}' se eliminó correctamente",
    "treepermissions.toast.groupdelete": "El grupo '{{group}}' se eliminó correctamente",
    "treepermissions.toast.userdelete": "El usuario '{{user}}' se eliminó correctamente",
    "treepermissions.toast.deleteselerror": "Es necesario seleccionar al menos un usuario, un rol o un grupo",
    "treepermissions.toast.assignselerror01": "Es necesario seleccionar al menos un usuario y un rol o grupo",
    "treepermissions.toast.assignselerror02": "Solo se permite un rol por usuario",
    "treepermissions.toast.assignselsuccess01": "El grupo y los roles se han agregado correctamente",
    "treepermissions.toast.assignselsuccess02": "Grupo y roles han sido reemplazados con éxito",
    "treepermissions.toast.assignselsuccess03": "Rol ha sido reemplazado con éxito",
    "treepermissions.toast.savedialogsuccesscreated": "Usuario creado con éxito",
    "treepermissions.toast.savedialogsuccessupdated": "Usuario actualizado con éxito",
    "treepermissions.toast.savedialogerror": "Se debe seleccionar al menos una funcionalidad",
    "treepermissions.toast.rulecreate": "La regla '{{rule}}' se creó correctamente",
    "treepermissions.toast.permissionscreate": "Permisos creados exitosamente",
    "treepermissions.toast.ruledelete": "La regla '{{rule}}' se eliminó correctamente",
    "treepermissions.toast.sequelizeerrorforeignkey": "Error, se hace referencia al registro en otra tabla",
};

var custom = {
    'label.filtro.anios': 'Años',
    'label.filtro.vinos': 'Vinos',
    'view.menu.gestionespacios': 'Gestión de espacios',
    'view.menu.gestionpuestos' : 'Gestión de puestos',
    'view.menu.ocupacionsalas': 'Ocupación de salas',
    'view.menu.ocupacionvending': 'Ocupación Vending',
    'view.menu.hernan': 'Hernan',
    'view.menu.parking': 'Parking',
    'view.menu.mobiliario': 'Mobiliario',
    'view.menu.software': 'Software',
    'view.menu.analisis': 'Análisis',
    'view.menu.reporting': 'Informes'
}
var translationsES = $.extend(true, appES, custom);