var appFR = {
    "equalizer.label.datos": 'Data',
    "equalizer.label.ordenar": 'Sorting',
    "equalizer.label.presentacion": 'Presentation',
    "equalizer.label.colores": 'Colors and legend',
    "equalizer.label.cabecerasyetiquetas": 'Headers and labels',
    "equalizer.label.cabecera": 'Headers ',
    "equalizer.label.superponeretiquetas": 'Overlay labels',
    "equalizer.label.etiquetashojas": 'Leaf labels',
    "equalizer.label.etiquetasvalores": 'Value labels',
    "equalizer.label.titulos": 'Titles',
    "equalizer.label.dimensiones": 'Dimensions',
    "equalizer.label.medidas": 'Measures',
    "equalizer.label.ascendente": 'Ascending',
    "equalizer.label.descendente": 'Descending',
    "equalizer.label.vertical": 'Vertical',
    "equalizer.label.horizontal": 'Horizontal',
    "equalizer.label.agrupado": 'Grouped',
    "equalizer.label.apilado": 'Stacked',
    "equalizer.label.valoresperdidos": 'Missing values',
    "equalizer.label.mostrarhuecos": 'Show as gaps',
    "equalizer.label.mostrarconexiones": 'Show as connections',
    "equalizer.label.mostrarceros": 'Show as zeros',
    "equalizer.label.mostrarpuntos": 'Show data points',
    "equalizer.label.tamanioburbuja": 'Bubble size',
    "equalizer.label.puntosfluctuacion": 'Jitter points',
    "equalizer.label.activado": 'On',
    "equalizer.label.desactivado": 'Off',
    "equalizer.label.personalizado": 'Custom',
    "equalizer.label.colorunico": 'Single color',
    "equalizer.label.porDimension": 'By dimension',
    "equalizer.label.porMedida": 'By measure',
    "equalizer.label.multicolor": 'Multicolored',
    "equalizer.label.esquemacolor": 'Color scheme',
    "equalizer.label.mostrarleyenda": 'Show legend',
    "equalizer.label.mostrartitulo": 'Show titles',
    "equalizer.label.mostraretiqueta": 'Show label',
    "equalizer.label.titulo": 'Title',
    "equalizer.label.subtitulo": 'Subtitle',
    "equalizer.label.piepagina": 'Footnote',
    "equalizer.label.posicionleyenda": 'Legend position',
    "equalizer.label.posicion": 'Position',
    "equalizer.label.automatico": 'Auto',
    "equalizer.label.derecha": 'Right',
    "equalizer.label.final": 'Bottom',
    "equalizer.label.izquierda": 'Left',
    "equalizer.label.principio": 'Top',
    "equalizer.label.etiquetavalores": 'Value labels',
    "equalizer.label.capas": 'Layers',
    "equalizer.label.configuracionmapa": 'Map settings',
    "equalizer.label.idiomamapa": 'Map language',
    "equalizer.label.capa.puntos": 'Point layer',
    "equalizer.label.capa.grafico": 'Chart layer',
    "equalizer.label.capa.lineas": 'Line layer',
    "equalizer.label.capa.densidad": 'Density layer',
    "equalizer.label.capa.area": 'Area layer',
    "equalizer.label.capa.fondo": 'Background layer',
    "equalizer.label.mapabase": 'Base map',
    "equalizer.label.prederminado": 'Default',
    "equalizer.label.palido": 'Pale',
    "equalizer.label.satelite": 'Satellite',
    "equalizer.label.ninguna": 'None',
    "equalizer.label.todos": 'All',
    "equalizer.label.cuota": 'Share',
    "equalizer.label.valores": 'Values',
    "equalizer.label.ingles": 'English',
    "equalizer.label.local": 'Local',
    "equalizer.label.zoomauto": 'Auto-zoom',
    "equalizer.label.mostrarcapa": 'Show layer',
    "equalizer.label.tamanioburbuja": 'Bubble size',
    "equalizer.label.rangoburbuja": 'Bubble size range',
    "equalizer.label.rangotriangulo": 'Triangle size range',
    "equalizer.label.rangocuadrado": 'Square size range',
    "equalizer.label.rangopentagono": 'Pentagon size range',
    "equalizer.label.rangohexagono": 'Hexagon size range',
    "equalizer.label.rangotarta": 'Pie chart size',
    "equalizer.label.rangolinea": 'Line width',
    "equalizer.label.radioinfluencia": 'Influence radiux',
    "equalizer.label.alto": 'Height',
    "equalizer.label.ancho": 'Width',
    "equalizer.label.navegacion": 'Navigation',
    "equalizer.label.etiquetas": 'Labels',
    "equalizer.label.linea": 'Line',
    "equalizer.label.area": 'Area',
    "equalizer.label.escalalogaritmica": 'Logarithmic scale',
    "equalizer.label.tarta": 'Pie',
    "equalizer.label.donut": 'Donut',
    "equalizer.label.colorespersistentes": 'Persistent colors',
    "equalizer.label.expandirtodo": 'Expand all',
    "equalizer.label.contraertodo": 'Collapse all',
    "equalizer.label.tablatotales": 'Totals',
    "equalizer.label.desplazamiento": 'Scrolling',
    "equalizer.label.inmovilizarColumna": 'Freeze first column',
    "equalizer.label.desHorizontal": 'Horizontal scrolling',
    "equalizer.label.ajustesTexto": 'Multiline text wrapping',
    "equalizer.label.textoCabecera": 'Wrap text in headers',
    "equalizer.label.textoCelda": 'Wrap text in cells',
    "equalizer.label.filtros": "Filters",
    "equalizer.btn.guardar": 'Save',
    "equalizer.btn.aplicar": 'Apply',
    "equalizer.btn.cancelar": 'Cancel',
    "equalizer.btn.cerrar": 'Close',
    "equalizer.btn.descartar": 'Discard',
    "equalizer.title.mover": 'Move',
    "equalizer.title.ascendente": 'Ascending',
    "equalizer.title.descendente": 'Descending',
    "equalizer.title.vertical": 'Vertical',
    "equalizer.title.horizontal": 'Horizontal',
    "equalizer.modal.atencion": 'Attention',
    "equalizer.modal.aviso": 'Changes have not been saved.',
    "equalizer.modal.cambios": 'Apply the changes?',
    "equalizer.modal.cambiosexplicacion": 'All changes will be applied to the properties of the object.',
    "equalizer.modal.errormensaje": 'Selection has created an inconsistency.',
    "equalizer.language.spaniol": 'Spanish',
    "equalizer.language.ingles": 'English',
    "equalizer.language.frances": 'French',
    "contextmenu.label.menuexploracion": 'Open exploration menu',
    "contextmenu.label.verdatos": 'View data',
    "contextmenu.label.vergrafico": 'View chart',
    "contextmenu.label.exportimagen": 'Export as an image',
    "contextmenu.label.exportpdf": 'Export to PDF',
    "contextmenu.label.exportdatos": 'Export data',
    "contextmenu.label.expandirtodo": 'Expand all',
    "contextmenu.label.contraertodo": 'Collapse all',
    "views.login.seleccionar": "Select language",
    "views.acciones.marcadores": "Bookmark",
    "views.acciones.ayuda": "Help",
    "views.acciones.aniadirmarcadores": "Add Bookmark",
    "views.acciones.mas": "More",
    "views.acciones.filtros": "Filters",
    "views.acciones.bloquear": "Lock",
    "views.acciones.desbloquear": "Unlock",
    "views.acciones.limpiarselecciones": "Clear selections",
    "views.acciones.crearmarcadores": "Create new bookmark",
    "views.acciones.seleccionartodos": "Select all",
    "views.acciones.eliminarseleccionados": "Delete selected",
    "views.acciones.OKbookmark": "The bookmark has been created",
    "views.acciones.KObookmark": "You must enter the name of the bookmark",
    "views.acciones.CrearBookmark": "The bookmark has been created",
    "views.acciones.EliminarBookmark": "The marker has been removed",
    "views.acciones.Bookmarkexiste": "A bookmark with this title already exists. Assign another title to the bookmark.",
    "views.acciones.seeliminaraBookmar": "The bookmark will be deleted.",
    'views.modal.crearmarcador': "Create bookmark",
    'views.modal.editarmarcador': "Edit Bookmark",
    "views.modal.crearmarcadortitulo": "Title",
    "views.modal.crearmarcadordescripcion": "Description",
    "views.modal.cerrar": "Close",
    "views.modal.exportar": "Export",
    "views.modal.crear": "Create",
    "views.modal.continuar": "Continue",
    "views.modal.aceptar": "Ok",
    "views.modal.atencion": "Attention",
    "views.modal.accionnoback": "This action can not be undone. Do you wish to continue?",
    "views.modal.pdf": "PDF configurations",
    "views.modal.tamaniopapel": "Paper size",
    "views.modal.carta": "Letter",
    "views.modal.orientacion": "Orientation",
    "views.modal.vertical": "Vertical",
    "views.modal.apaisado": "Landscape",
    "views.modal.opcionesaspecto": "Aspect ratio options",
    "views.modal.actual": "Keep current size",
    "views.modal.ajustar": "Fit to page",
    "views.modal.selectkpi": "Select a KPI",
    "views.modal.configuracion": "Settings",
    "views.label.selecciones": "Selections",
    "views.label.filtros": "Filters",
    "views.label.glosario": "Glossary",
    "views.label.cerrar": "Close",
    "views.label.DimensionesMedidas": "Dimensions and Measurements",
    "views.label.buscar": "Search for",
    "template.label.template": "Template skin customizer",
    "template.label.themes": "Custom themes",
    "template.label.sidebarimages": "Sidebar Background Imagen",
    "template.label.sidebarcolor": "Sidebar Background Cover Color",
    "template.label.headercolor": "Header Background  Color", 
    "template.label.backgroundimage": "Background image",
    "template.label.menucolor": "Menu color",
    "template.label.saveconfig": "Save settings",
    "template.label.cliente": "Client",
    "template.label.proyecto": "Project",
    "template.label.enlazarhoja": "Link to sheet",
    "template.label.seleccionarhoja": "Select a sheet",
    "views.idioma.es": "Spanish",
    "views.idioma.en": "English",
    "views.idioma.fr": "French",
};
var custom = {
    'label.filtro.anios': 'Years',
    'label.filtro.vinos': 'Wines',
    'view.menu.gestionespacios': 'Space management',
    'view.menu.gestionpuestos': 'Management positions',
    'view.menu.ocupacionsalas': 'Room Occupancy',
    'view.menu.ocupacionvending': 'Vending occupation',
    'view.menu.hernan': 'Hernan',
    'view.menu.parking': 'Parking',
    'view.menu.mobiliario': 'Furniture',
    'view.menu.software': 'Software',
    'view.menu.analisis': 'Analysis',
    'view.menu.reporting' : 'Reporting'
}
var translationsFR = $.extend(true, appFR, custom);